name: Run Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and run tests
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        build-args: |
          ARG1=value1
          ARG2=value2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

